### ISSUE TITLE
calling `search` modifies the method `search`, so it can only be called once. 

### ISSUE THREAD

**Issue by ljwolf** [pysal/gwr#16]
When you call `Sel_BW(...).search(criterion='something', search='something')`, the search method actually overwrites itself on [line 172](https://github.com/pysal/gwr/blob/master/gwr/sel_bw.py#L171). So you can't run it again without instantiating it again, and the error is really cryptic (since search is now a string, you get "str object is not callable" when you've not done anything with strings?)

I'd like to change this to assign to `self.search_method` or something.

**Comment by TaylorOshan** [comment]
Definitely not a feature! Changing from ``self.search`` to ``self.search_method`` seems like a solid straight forward solution.

**Comment by ljwolf** [comment]
will ship with #13 then

**Comment by ljwolf** [comment]
resolved by 13
