### ISSUE TITLE
GWR speed-up

### ISSUE THREAD

**Issue by Ziqi-Li** [pysal/gwr#4]
Two speed-up ideas
1. Calculate only AIC/AICc/BIC/CV (search method) in bandwidth searching and calculate **full diagnostics** in the final `GWR.fit()`. I am planning to submit a PR about this.

2. When calculating kernel for each bandwidth, distance matrix is calculated and sorted (if `fixed = False`) every time, which can be calculated for only once and passed to kernel calculation function.

**Comment by TaylorOshan** [comment]
Part 1 of this issue is addressed in #8 but was ultimately taken left for a future PR after some profiling.

Part 2 was satisfied in #10
